### ISSUE TITLE
change lib

### ISSUE THREAD

**Issue by renan-fazzani** [tripflex/captive-portal-wifi-setup#11]
hi, i need to change the lib so that it gives me a ssid return, whenever i open the captive portal.
that way I can know on which network the esp8266 is configured.
could you help me?

**Comment by tripflex** [comment]
Not sure what you mean by this?  This specific library is for testing and setting up wifi connection, has nothing to do with "gives me a ssid return"  ... if you want to know what network the device is configured for you just read the configuration file

**Comment by renan-fazzani** [comment]
hi, I understand what this lib is for, but I wanted help to know how to read this configuration file to implement my own lib, could you help me?
