### ISSUE TITLE
I am getting build errors on library source code

### ISSUE THREAD

**Issue by fabiohmantelli** [tripflex/captive-portal-wifi-setup#12]
I added the library in the mos.yml file, however, I get some build errors in the library source code.

`  CC    /c/projects/testes/wifi-setup-web/deps/rpc-common/src/mgos_rpc.c
/c/projects/testes/wifi-setup-web/deps/captive-portal-wifi-setup/src/mgos_captive_portal_wifi_setup.c: In function 'mgos_captive_portal_wifi_setup_test_ent':
/c/projects/testes/wifi-setup-web/deps/captive-portal-wifi-setup/src/mgos_captive_portal_wifi_setup.c:227:18: error: 'struct mgos_config_wifi_sta' has no member named 'protocol'
  227 |  sp_test_sta_vals->protocol = mgos_sys_config_get_wifi_sta_protocol();
      |                  ^~
/c/projects/testes/wifi-setup-web/deps/captive-portal-wifi-setup/src/mgos_captive_portal_wifi_setup.c:227:31: error: implicit declaration of function 'mgos_sys_config_get_wifi_sta_protocol'; did you mean 'mgos_sys_config_get_wifi_sta_netmask'? 
[-Werror=implicit-function-declaration]
  227 |  sp_test_sta_vals->protocol = mgos_sys_config_get_wifi_sta_protocol();
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                               mgos_sys_config_get_wifi_sta_netmask
/c/projects/testes/wifi-setup-web/deps/captive-portal-wifi-setup/src/mgos_captive_portal_wifi_setup.c: In function 'mgos_captive_portal_wifi_setup_test':
/c/projects/testes/wifi-setup-web/deps/captive-portal-wifi-setup/src/mgos_captive_portal_wifi_setup.c:252:18: error: 'struct mgos_config_wifi_sta' has no member named 'protocol'
  252 |  sp_test_sta_vals->protocol = mgos_sys_config_get_wifi_sta_protocol();
      |                  ^~
  CC    /c/projects/testes/wifi-setup-web/deps/captive-portal-wifi-rpc/src/mgos_captive_portal_wifi_rpc.c
cc1: all warnings being treated as errors
/c/projects/testes/wifi-setup-web/deps/modules/mongoose-os/platforms/esp8266/Makefile.build:380: recipe for target '/c/projects/testes/wifi-setup-web/build/objs/mgos_captive_portal_wifi_setup.c.o' failed
make: *** [/c/projects/testes/wifi-setup-web/build/objs/mgos_captive_portal_wifi_setup.c.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/app'
Error: exit status 2
/src/cli/build_local.go:697:
/src/cli/build_local.go:684:
/src/cli/build_local.go:449:
/src/cli/build.go:270:
/src/cli/build.go:213:
/src/cli/main.go:198: build failed`

**Comment by tripflex** [comment]
Looks like this was introduced here:
https://github.com/tripflex/captive-portal-wifi-setup/commit/5ce99a5ce9d306b3621ff4d4a7c350603a4d9e50
https://github.com/tripflex/captive-portal-wifi-setup/pull/10

So looks like this should ONLY be done on ESP32, whereas you're using an ESP8266 it looks like which is the reason for the error.

**Comment by tripflex** [comment]
@fabiohmantelli okay please remove everything from `deps` dir and try to build again, the issue was as mentioned above, protocol was being set on every device, when should only be set on ESP32 devices.

**Comment by fabiohmantelli** [comment]
I have tried removing the deps dir and still had no success. I have tried rebuilding specifying the ESP32 platform and it worked, so it looks like I will have to find another solution to my embedded web page on my ESP8266. Tks

**Comment by tripflex** [comment]
@fabiohmantelli what error were you getting?  Don't specify the ESP32 platform if you're using ESP82666 ... the original error you reported though was fixed in the latest release, but make sure you clean your deps directory so it pulls the latest

**Comment by fabiohmantelli** [comment]
Hello, I have since moved on to another embedded webpage solution, using a custom webpage along with the mongoose-os standard libs.
