### ISSUE TITLE
Callback fired twice

### ISSUE THREAD

**Issue by janainascal** [tripflex/captive-portal-wifi-setup#8]
When setted the callback for `MGOS_CAPTIVE_PORTAL_WIFI_SETUP_TEST_SUCCESS`, it also sets the same callback for `MGOS_WIFI_EV_STA_IP_ACQUIRED`, so it needs to remove it inside the callback.
Why?!

When setted the callback for `MGOS_CAPTIVE_PORTAL_WIFI_SETUP_TEST_FAILED` the same happens but I don't know what event is also setted.

I using frozen do read pass and ssid from the rpc callback, and it needs to free the heap for these variables, but because this bug, it calls the `free` function twice.  

```
static void test_success_cb(int ev, void *ev_data, void *userdata)
{
  mgos_event_remove_handler(MGOS_WIFI_EV_STA_IP_ACQUIRED, test_success_cb, NULL);
  ...
  free(ssid);
  free(pass);
}
```

**Comment by tripflex** [comment]
I'm a bit confused by what you're asking/saying?  Yes this library uses the `MGOS_WIFI_EV_STA_IP_ACQUIRED` event to determine if the connection was using the test SSID, and then makes the event call for `MGOS_CAPTIVE_PORTAL_WIFI_SETUP_TEST_SUCCESS` or `MGOS_CAPTIVE_PORTAL_WIFI_SETUP_TEST_FAILED`

**Comment by janainascal** [comment]
The callback runs twice.
I set the callback for `MGOS_CAPTIVE_PORTAL_WIFI_SETUP_TEST_FAILED` and it runs twice.

**Comment by janainascal** [comment]
it is called twice:
```
[Oct 17 21:56:05.161] mgos_wifi.c:136         WiFi STA: Connected, BSSID 00:1a:3f:97:c5:da ch 1 RSSI -46
[Oct 17 21:56:05.161] mgos_net.c:89           WiFi STA: connected
[Oct 17 21:56:09.106] ip:10.0.0.105,mask:255.255.255.0,gw:10.0.0.1
[Oct 17 21:56:09.106] main.c:30               callback here
[Oct 17 21:56:09.106] main.c:30               callback here
```
`mgos_net` is from [mongosse-os](https://github.com/cesanta/mongoose-os) core and `mgos_wifi` is from [mongoose-os-libs](https://github.com/mongoose-os-libs/wifi)  
Both defines its events types as enum with DISCONNETC = 0 and IP_AQUIRED = 3.

So far I don't know how to handle this, hope someone does.

**Comment by janainascal** [comment]
This was solved when I set the events before initialization
```
void mgos_app_preinit()
{
  mgos_event_add_handler(MGOS_CAPTIVE_PORTAL_WIFI_SETUP_TEST_SUCCESS, test_success_cb, NULL);
  mgos_event_add_handler(MGOS_CAPTIVE_PORTAL_WIFI_SETUP_TEST_FAILED, test_failed_cb, NULL);
  mgos_event_add_handler(MGOS_WIFI_EV_STA_IP_ACQUIRED, sta_ip_acquired_cb, NULL);
}
```
